### PR TITLE
Add Scan method for ResultSet to scan the rows into the given slice (Part 1)

### PR DESCRIPTION
**Pull request by haoxins**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

#### Issue(s) number: 

https://github.com/vesoft-inc/nebula-go/issues/296
#### Description:

This PR includes changes in https://github.com/vesoft-inc/nebula-go/pull/297,
I add the first draft implementation for the API proposed in https://github.com/vesoft-inc/nebula-go/issues/296.

Some tasks need to be done, such as

- [ ] Support all the fundamental types;
- [ ] Support nest structure type;
- [ ] Add more tests.

But I raised this PR as a draft in case there are some potential concerns from your guys.
So feel free to leave some comments here.

Such as can we drop support for Go versions that `< 1.18`?

cc @wey-gu @veezhang

### CODE REVIEW

**Comment by haoxins** [comment]
@wey-gu @veezhang Any thoughts?

**Comment by Nicole00** [comment]
some ci failures need to be deal due to the go version.

**Comment by haoxins** [comment]
> some ci failures need to be deal due to the go version.

@Nicole00 may I just removed the go versions `<1.18`?

**Comment by Nicole00** [comment]
> > some ci failures need to be deal due to the go version.
> 
> @Nicole00 may I just removed the go versions `<1.18`?

For now we can't remove the go version yet. Because it will confluence the users' usage when upgrade the nebula-go.

**Comment by haoxins** [comment]
> > > some ci failures need to be deal due to the go version.
> > 
> > 
> > @Nicole00 may I just removed the go versions `<1.18`?
> 
> For now we can't remove the go version yet. Because it will confluence the users' usage when upgrade the nebula-go.

ok, I will remove the usage of `lo` which requires Go `1.18`+

**Comment by haoxins** [comment]
> > > some ci failures need to be deal due to the go version.
> > 
> > 
> > @Nicole00 may I just removed the go versions `<1.18`?
> 
> For now we can't remove the go version yet. Because it will confluence the users' usage when upgrade the nebula-go.

@Nicole00 I have added the Go 1.16+ back

**Comment by haoxins** [comment]
@Nicole00 any other comments?

**Review by Nicole00 — APPROVED** [review]

**Pull request merged**
