### PR TITLE
Add stmt wrapper

### PR DESCRIPTION
**Pull request by Ranxy**
#111 
Unlike this issues, this implementation uses ? {} as a parameter template, because {} conflicts with match.

### CODE REVIEW

**Comment by wey-gu** [comment]
Thank you @Ranxy!
@Aiee @laura-ding could you help review? this seems to introduce an escaped template charactor.

**Comment by Aiee** [comment]
Hi,
I noticed the implementation you provided is more like to re-assemble the query string with customized parameters. One drawback is that the user still needs to memorize the ngql grammar, such as `"INSERT VERTEX v1 (p1, p2)`.

I believe something like [py2neo](https://py2neo.org/2021.1/index.html) is really what we want since it offers a high-level encapsulation of the query.

**Comment by Ranxy** [comment]
@Aiee It is true that this method is still troublesome to use, looking forward to an exciting solution from @everywan.

**Comment by everywan** [comment]
> Hi,
> I noticed the implementation you provided is more like to re-assemble the query string with customized parameters. One drawback is that the user still needs to memorize the ngql grammar, such as `"INSERT VERTEX v1 (p1, p2)`.
> 
> I believe something like [py2neo](https://py2neo.org/2021.1/index.html) is really what we want since it offers a high-level encapsulation of the query. The proposal made by @everywan in #114 seems like a good approach to it. Let's see how would that go.

Will be this week!

**Comment by wey-gu** [comment]
> @Aiee It is true that this method is still troublesome to use, looking forward to an exciting solution from @everywan.

Thank you @Ranxy for spending your time sharing your work with everyone in the nebula community :).
It's priceless to us!!!

**Pull request closed without merging**
