### PR TITLE
Introducing EntityBuilder

### PR DESCRIPTION
**Pull request by haoxins**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

#### Description:

Hi,

I'm introducing the EntityBuilder from my personal work on Nebula Vertex/Edge creation.
I only implement the UPSERT because I only use UPSERT currently.
But this feature is a wide requirement.
I will continue to implement the rest of the logic if you guys think this can be considered the built-in function in the Nebula Go SDK.

cc @Nicole00 and @wey-gu

### CODE REVIEW

**Comment by haoxins** [comment]
@Nicole00 do you think I should continue to work on this?

**Comment by Nicole00** [comment]
> I'm introducing the EntityBuilder from my personal work on Nebula Vertex/Edge creation.
> I only implement the UPSERT because I only use UPSERT currently.
> But this feature is a wide requirement.
> I will continue to implement the rest of the logic if you guys think this can be considered the built-in function in the Nebula Go SDK.

It's really a very useful function for users. I prefer to do it in an ORM-like tool on  the base of go SDK.

**Comment by haoxins** [comment]
yeah, make sense.
i will start it from a new repo.

**Comment by haoxins** [comment]
I created a new repo https://github.com/haoxins/nebula-ent for this.

**Comment by Nicole00** [comment]
> I created a new repo https://github.com/haoxins/nebula-ent for this.

Great！Thanks for your sustained contribution, I'll create a new repo for this in https://github.com/nebula-contrib.

**Comment by Nicole00** [comment]
@haoxins please check your email and commit your project to this repo：https://github.com/nebula-contrib/nebula-go-builder
image

**Comment by wey-gu** [comment]
It's actually a golang graph orm, right?

how about go-graphizer ?

**Pull request closed without merging**
