### PR TITLE
fix session leak

### PR DESCRIPTION
**Pull request by zjtaozjtw**
## What type of PR is this?
- [x] bug
- [ ] feature
- [ ] enhancement

#### Issue(s) number: 
#268 

## How do you solve it?

当new session 后，及时更新当前使用的session引用

### CODE REVIEW

**Review by wey-gu — APPROVED** [review]
Thanks!

**Comment by HarrisChu** [comment]
this pr would  simply fix the issue, but we process session in separate functions. (new session, update or push to list) 
prefer refactor those functions... 
@Aiee WDYT

**Comment by HarrisChu** [comment]
maybe we would quick fix first, and then enhance these code in future

**Comment by Aiee** [comment]
> maybe we would quick fix first, and then enhance these code in future

Makes sense to me.

**Review by HarrisChu — APPROVED** [review]

**Review by Aiee — APPROVED** [review]
Nice catch! Thanks for your contribution.

**Pull request merged**
