### PR TITLE
Support the tck format for the output of EXPLAIN

### PR DESCRIPTION
**Pull request by AntiTopQuark**
## What type of PR is this?
- [ ] bug
- [x] feature
- [ ] enhancement

#### Issue(s) number: 
https://github.com/vesoft-inc/nebula/issues/5274

#### Description:
Support the tck format for the output of EXPLAIN

## How do you solve it?
In `nebula-go`,I have added a function called `MakePlanByTck()`, which is designed to return TCK-formatted result sets for the `Nebula Console`. 

The `MakePlanByTck()` function will sequentially add columns for `dependencies`, `profiling data`, and empty `operator info`. 

Since `profiling data` and `operator info ` are also needed in the Row-formatted, the logic for generating `profiling data` and `operator info` have been separated into individual functions `MakeProfilingData()` and `MakeOperatorInfo()` for reusability.

## Special notes for your reviewer, ex. impact of this fix, design document, etc:
related link:
- the pr link of nebula repo: https://github.com/vesoft-inc/nebula/pull/5414
- the pr link of nebula-console: https://github.com/vesoft-inc/nebula-console/pull/210
- the pr link of nebula nebula-go:https://github.com/vesoft-inc/nebula-go/pull/265
- the pr link of nebula-doc:https://github.com/vesoft-inc/nebula-docs/pull/2017
- the pr link of nebula-doc-cn:https://github.com/vesoft-inc/nebula-docs-cn/pull/2664

### CODE REVIEW

**Review by jievince — APPROVED** [review]
Good job

**Review by Aiee — COMMENTED** [review]
Could you add some tests to this PR? You could choose a test case from the `.feature` files from the Nebula repo and add it here.

**Comment by Aiee** [comment]
> 

Makes sense.

**Comment by Aiee** [comment]
> 

Makes sense.

**Pull request merged**
